CREATE DATABASE CarShopDB;
GO

USE CarShopDB;
GO

CREATE TABLE Customer (
Id INT PRIMARY KEY,
Name NVARCHAR(100) NOT NULL,
PhoneNumber INT,
Payment BIT NOT NULL DEFAULT 0);

CREATE TABLE Car (
Id INT PRIMARY KEY,
Model NVARCHAR(100) NOT NULL,
Brand NVARCHAR(100) NOT NULL,
Year INT,
RegNumber NVARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE CustomerCar (
Id INT PRIMARY KEY,
CarId INT NOT NULL,
CustomerId INT NOT NULL,
Task NVARCHAR(100) NOT NULL,
Price DECIMAL (10, 2),
ETA DATETIME,
FOREIGN KEY (CarId) REFERENCES Car(Id),
FOREIGN KEY (CustomerId) REFERENCES Customer(Id)
);

CREATE TABLE CustomerRental (
Id INT PRIMARY KEY, 
CarId INT NOT NULL,
CustomerId INT NOT NULL,
StartDate DATETIME,
EndDate DATETIME,
FOREIGN KEY (CarId) REFERENCES Car(Id),
FOREIGN KEY (CustomerId) REFERENCES Customer(Id)
);